Update AllColumnNamesValueReader.cs (#73)
* Update AllColumnNamesValueReader.cs

Columns with empty names are added to ExcelHeading.ColumnNames, but not added to the ExcelHeading.NameMapping
this results in the following exception being thrown when attempting to map to a Dictionary after ExcelHeading.GetColumnIndex is called

ExcelMapper.ExcelMappingException: Column "" does not exist in ["header1", "header2", "header3"]
   at ExcelMapper.ExcelHeading.GetColumnIndex(String columnName)
   at ExcelMapper.Readers.AllColumnNamesValueReader.<>c__DisplayClass0_0.<TryGetValues>b__0(String columnName)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at ExcelMapper.ManyToOneDictionaryMap`1.TryGetValue(ExcelSheet sheet, Int32 rowIndex, IExcelDataReader reader, MemberInfo member, Object& value)
   at ExcelMapper.ExcelClassMap.TryGetValue(ExcelSheet sheet, Int32 rowIndex, IExcelDataReader reader, MemberInfo member, Object& result)
   at ExcelMapper.ExcelSheet.TryReadRow[T](T& value)

* adding test and test file

* updating test with proper asserts, and using proper file

Co-authored-by: Robert Fernandes <robert.fernandes@jsitelecom.com>